routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::post('blog/search', 'BlogController@searchPost')->name('admin.blog.search');
Route::get('/blog/{slug}', 'BlogController@getSingle')->name('blog.single');

Route::get('/blog', 'BlogController@getIndex')->name('blog.index');

Route::get('/about', 'PagesController@getAbout');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/logout', 'Auth\LoginController@userLogout')->name('user.logout');

Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/admin/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

Route::get('/admin/register', 'Auth\AdminRegisterController@showRegistrationForm')->name('admin.register');
Route::post('/admin/register', 'Auth\AdminRegisterController@register')->name('admin.register.submit');

Route::post('/user/password/update', 'PasswordController@update')->name('user.password.update');
Route::get('/user/password', 'PasswordController@show')->name('user.password');
Route::post('/user/update', 'UserController@update')->name('user.update');
Route::get('/user', 'UserController@show')->name('user');

Route::post('/admin/password/update', 'AdminPasswordController@update')->name('admin.password.update');
Route::get('/admin/password', 'AdminPasswordController@show')->name('admin.password');


Route::post('/admin/posts/search', 'AdminPostController@searchPost')->name('admin.posts.search');
Route::get('/admin/posts/block', 'AdminPostController@indexBlock')->name('admin.posts.index.block');
Route::get('/admin/posts', 'AdminPostController@index')->name('admin.posts.index');
Route::get('/admin/posts/{post}', 'AdminPostController@show')->name('admin.posts.show');
Route::put('/admin/posts/{post}', 'AdminPostController@update')->name('admin.posts.update');
Route::delete('/admin/posts/{post}', 'AdminPostController@destroy')->name('admin.posts.destroy');


Route::get('/admin/users/posts/{post}', 'AdminPostController@showUser')->name('admin.user.posts.show');
Route::put('/admin/users/posts/{post}', 'AdminPostController@updateUser')->name('admin.user.posts.update');
Route::delete('/admin/users/posts/{post}', 'AdminPostController@destroyUser')->name('admin.user.posts.destroy');

Route::post('/admin/users/search', 'AdminUserController@searchUser')->name('admin.users.search');
Route::get('/admin/users/block', 'AdminUserController@indexBlock')->name('admin.users.index.block');
Route::get('/admin/users', 'AdminUserController@index')->name('admin.users.index');
Route::get('/admin/users/{user}', 'AdminUserController@show')->name('admin.users.show');
Route::put('/admin/users/{user}', 'AdminUserController@update')->name('admin.users.update');
Route::delete('/admin/users/{user}', 'AdminUserController@destroy')->name('admin.users.destroy');


Route::get('/admin/user', 'AdminController@show')->name('admin.user');
Route::post('/admin/update', 'AdminController@update')->name('admin.user.update');

Route::get('/admin', 'AdminController@index')->name('admin');

Route::get('/', 'PagesController@getIndex');

Route::resource('posts', 'PostController');
Route::resource('comments', 'CommentController');

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('title', ' | All Post')

@section('content')
    <div class="row">
        <div class="col-md-8 offset-md-1">
            <h1>All Post</h1>
        </div>
        <div class="col-md-2">
            <button class="searchBlog btn btn-lg btn-block btn-primary" >Search Post</button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="searchForm" style="display: none;">
                <div class="card">
                    <div class="card-header">{{ __('Post Search') }}</div>
    
                    <div class="card-body">
    
                        <form method="POST" action="{{ route('admin.posts.search') }}" aria-label="{{ __('Register') }}">
                            @csrf
    
                            <div class="form-group row">
                                <label for="title" class="col-md-2 col-form-label text-md-right">{{ __('Title') }}</label>
                                <div class="col-md-8">
                                    <input id="title" type="text"
                                        class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title"
                                        value="{{ old('title') }}" >
    
                                        @if ($errors->has('title'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('title') }}</strong>
                                            </span>
                                        @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="user"
                                    class="col-md-2 col-form-label text-md-right">{{ __('Auhtor') }}</label>
                                <div class="col-md-8">
                                    <input id="user" type="text"
                                        class="form-control{{ $errors->has('user') ? ' is-invalid' : '' }}" name="user"
                                        value="{{ old('user') }}" >
    
                                        @if ($errors->has('user'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('user') }}</strong>
                                            </span>
                                        @endif
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="city" class="col-md-2 col-form-label text-md-right">{{ __('City') }}</label>
                                <div class="col-md-8">
                                    <input id="city" type="text"
                                        class="form-control" name="city"
                                        value="{{ old('city') }}" >
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="country"
                                    class="col-md-2 col-form-label text-md-right">{{ __('Country') }}</label>
                                <div class="col-md-8">
                                    <input id="country" type="text"
                                        class="form-control"
                                        name="country" value="{{ old('country') }}" >
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="from" class="col-md-2 col-form-label text-md-right">{{ __('From') }}</label>
                                <div class="col-md-8">
                                    <input id="from" type="date"
                                        class="form-control{{ $errors->has('from') ? ' is-invalid' : '' }}" name="from"
                                        value="{{ old('from') }}" >
    
                                        @if ($errors->has('from'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('from') }}</strong>
                                            </span>
                                        @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="to" class="col-md-2 col-form-label text-md-right">{{ __('To') }}</label>
                                <div class="col-md-8">
                                    <input id="to" type="date"
                                        class="form-control{{ $errors->has('to') ? ' is-invalid' : '' }}" name="to"
                                        value="{{ old('to') }}" >
    
                                        @if ($errors->has('to'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('to') }}</strong>
                                            </span>
                                        @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-2 offset-md-5">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        {{ __('Search') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 offset-md-1">
            <table class="table" style="margin-top: 20px;">
                <thead>
                    <th style="width: 35%">Title</th>
                    <th style="width: 45%">Body</th>
                    <th style="width: 15%">Create At</th>
                    <th style="width: 5%"></th>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td>{{ $post->title }}</td>
                            <td>{{ substr($post->body, 0, 250) }}{{ strlen($post->body)>250 ? "..." : ""}}</td>
                            <td>{{ date('M j, Y h:iA', strtotime($post->created_at)) }}</td>
                            <td>
                                <div class="row">
                                    <a href="{{ route('admin.posts.show', $post->id)}}" class="btn btn-primary btn-block">View</a>
                                    {!! Form::open(['route'=>['admin.posts.update', $post->id], 'method' => 'PUT']) !!}
                                    {!! Form::submit($post->block ? 'Unblock' : 'Block', ['class'=>$post->block ? 'btn btn-danger btn-block' : 'btn btn-warning btn-block', 'style'=>'margin-top: 10px; width: 80px;']) !!}
                                    {!! Form::close() !!}
                                    {!! Form::open(['route'=>['admin.posts.destroy', $post->id], 'method' => 'DELETE']) !!}
                                    {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-block', 'style'=>'margin-top: 10px; width: 80px;']) !!}
                                    {!! Form::close() !!}
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            
            <hr>

            <div class="" style="display: flex; justify-content: center;">
                {!! $posts->links(); !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/show-user-post.blade.php
@extends('layouts.app')

@section('title', ' | View Post')

@section('content')

<div class="row">
    <div class="col-sm-7 offset-sm-1">
        <h1>{{ $post->title }}</h1>
        <p class="lead"> {{ $post->body }}</p>
    </div>

    <div class="col-sm-2 offset-sm-1">
        <div class="well">
            <dl class="dl-horizontal">
                <dt>URL:</dt>
                <dd><a href="{{ route('blog.single',$post->slug) }}">{{substr(url('blog/'.$post->slug), 0 ,20)}}{{ strlen(url($post->slug))>20 ? "..." : ""}}</a></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Create At:</dt>
                <dd>{{date('M j, Y h:iA', strtotime($post->created_at))}}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Last Update At:</dt>
                <dd>{{date('M j, Y h:iA', strtotime($post->updated_at))}}</dd>
            </dl>
            <div class="row">
                <div class="col-sm-6">
                    {!! Form::open(['route'=>['admin.user.posts.update', $post->id], 'method' => 'PUT']) !!}
                    {!! Form::submit($post->block ? 'Unblock' : 'Block', ['class'=>$post->block ? 'btn btn-danger btn-block' : 'btn btn-warning btn-block']) !!}
                    {!! Form::close() !!}
                </div>
                <div class="col-sm-6">
                    {!! Form::open(['route'=>['admin.user.posts.destroy', $post->id], 'method' => 'DELETE']) !!}
                    {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-block']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    {{ Html::linkRoute('admin.users.show', '<< See All Posts of User', $post->user_id, ['class' => 'btn btn-primary btn-block', 'style'=>'margin-top: 10px; align-items:center;'])}}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/show.blade.php
@extends('layouts.app')

@section('title', ' | View Post')

@section('content')

<div class="row">

    <div class="col-sm-7 offset-sm-1">
        <h1>{{ $post->title }}</h1>
        <p class="lead"> {{ $post->body }}</p>
    </div>

    <div class="col-sm-2 offset-sm-1">
        <div class="well">
            <dl class="dl-horizontal">
                <dt>URL:</dt>
                <dd><a href="{{ route('blog.single',$post->slug) }}">{{substr(url('blog/'.$post->slug), 0 ,20)}}{{ strlen(url($post->slug))>20 ? "..." : ""}}</a></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Create At:</dt>
                <dd>{{date('M j, Y h:iA', strtotime($post->created_at))}}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Last Update At:</dt>
                <dd>{{date('M j, Y h:iA', strtotime($post->updated_at))}}</dd>
            </dl>
            <div class="row">
                <div class="col-sm-6">
                    {!! Form::open(['route'=>['admin.posts.update', $post->id], 'method' => 'PUT']) !!}
                    {!! Form::submit($post->block ? 'Unblock' : 'Block', ['class'=>$post->block ? 'btn btn-danger btn-block' : 'btn btn-warning btn-block']) !!}
                    {!! Form::close() !!}
                </div>
                <div class="col-sm-6">
                    {!! Form::open(['route'=>['posts.destroy', $post->id], 'method' => 'DELETE']) !!}
                    {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-block']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    {{ Html::linkRoute('admin.posts.index', '<< See All Posts', [], ['class' => 'btn btn-primary btn-block', 'style'=>'margin-top: 10px; align-items:center;'])}}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/users-show.blade.php
@extends('layouts.app')

@section('title', ' | All Post')

@section('content')

    @if (Session::has('success'))
        <div class="row">
            <div class="col-md-10 offset-md-1 alert alert-danger alert-dismissible fade show" role="alert">
                <p>{{ Session::get('success') }}</p>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header" style="text-align: center;">
                    <h4>USER DETAIL</h4>
                </div>
                
                <div class="card-body">
                    
                    <div class="row align-items-center">
                        <div class="col-sm-4 offset-sm-4" >
                            <img  src="{{URL::to("$user->image")}}" alt="User Image" style='width: 100px;height: 100px; border-radius: 50%; margin-left: 25px; margin-right: 10px;
                            object-fit: cover;'>
                        </div>
                    </div>

                    <div class="row" style="margin-top:20px;">
                        <label class="col-sm-3 offset-sm-3 ">Name</label>
                        <div class="col-sm-3">
                            <p>{{ $user->name }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-3 offset-sm-3 ">Email</label>
                        <div class="col-sm-3">
                            <p>{{ $user->email }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-3 offset-sm-3 ">Address</label>
                        <div class="col-sm-3">
                            <p>{{ $user->city.", ".$user->country }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-3 offset-sm-3 ">Gender</label>
                        <div class="col-sm-3">
                            <p>{{ $user->gender }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-3 offset-sm-3 ">Age</label>
                        <div class="col-sm-3">
                            <p>{{ $user->age." years" }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-3 offset-sm-3 ">Create At</label>
                        <div class="col-sm-3">
                            <p>{{ date('M j, Y ', strtotime($user->created_at)) }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="margin-top: 50px;">
        <div class="col-md-6 offset-md-1">
            <h1>All Post</h1>
        </div>
        <div class="col-md-2">
            {!! Form::open(['route'=>['admin.users.update', $user->id], 'method' => 'PUT']) !!}
            {!! Form::submit($user->block ? 'Unblock User' : 'Block User', ['class'=>$user->block ? 'btn btn-danger btn-block' : 'btn btn-warning btn-block', 'style'=>'height: 45px;']) !!}
            {!! Form::close() !!}
        </div>
        <div class="col-md-2">
            <a href="{{ route('posts.create') }}" class="btn btn-lg btn-block btn-primary">Search Post</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 offset-md-1">
            <table class="table" style="margin-top: 20px;">
                <thead>
                    <th style="width: 35%">Title</th>
                    <th style="width: 45%">Body</th>
                    <th style="width: 15%">Create</th>
                    <th style="width: 5%"></th>
                </thead>
                <tbody>
                        @foreach($user->posts as $post)
                            <tr>
                                <td>{{ $post->title }}</td>
                                <td>{{ substr($post->body, 0, 250) }}{{ strlen($post->body)>250 ? "..." : ""}}</td>
                                <td>{{ date('M j, Y h:iA', strtotime($post->created_at)) }}</td>
                                <td>
                                    <div class="row">
                                        <a href="{{ route('admin.user.posts.show', $post->id)}}" class="btn btn-primary btn-block">View</a>
                                        {!! Form::open(['route'=>['admin.user.posts.update', $post->id], 'method' => 'PUT']) !!}
                                        {!! Form::submit($post->block ? 'Unblock' : 'Block', ['class'=>$post->block ? 'btn btn-danger btn-block' : 'btn btn-warning btn-block', 'style'=>'margin-top: 10px; width: 80px;']) !!}
                                        {!! Form::close() !!}
                                        {!! Form::open(['route'=>['admin.user.posts.destroy', $post->id], 'method' => 'DELETE']) !!}
                                        {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-block', 'style'=>'margin-top: 10px; width: 80px;']) !!}
                                        {!! Form::close() !!}
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                </tbody>
            </table>

            <hr>
            
        </div>
    </div>
@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('title', ' | All Post')

@section('content')

    @if (Session::has('blocked'))

        <div class="row">
            <div class="col-md-10 offset-md-1 alert alert-danger alert-dismissible fade show" role="alert">
                <p>{{ Session::get('blocked') }}</p>
            </div>
        </div>

    @elseif (Session::has('unblocked'))

        <div class="row">
            <div class="col-md-10 offset-md-1 alert alert-primary alert-dismissible fade show" role="alert">
                <p>{{ Session::get('unblocked') }}</p>
            </div>
        </div>

    @elseif (Session::has('success'))

        <div class="row">
            <div class="col-md-10 offset-md-1 alert alert-primary alert-dismissible fade show" role="alert">
                <p>{{ Session::get('success') }}</p>
            </div>
        </div>

    @endif

    <div class="row">
        <div class="col-md-8 offset-md-1">
            <h1>All User</h1>
        </div>
        <div class="col-md-2">
            <button class="searchBlog btn btn-lg btn-block btn-primary" >Search User</button>
        </div>
    </div>

    <div class="row" style="margin:10px;">
        <div class="col-md-8 offset-md-2">
            <div class="searchForm" style="display: none;">
                <div class="card">
                    <div class="card-header text-center"><h3>{{ __('Post Search') }}</h3></div>
    
                    <div class="card-body">
    
                        <form method="POST" action="{{ route('admin.users.search') }}" aria-label="{{ __('Register') }}">
                            @csrf
    
                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>
                                <div class="col-md-8">
                                    <input id="name" type="text"
                                        class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"
                                        value="{{ old('name') }}" >
    
                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email"
                                    class="col-md-2 col-form-label text-md-right">{{ __('Email') }}</label>
                                <div class="col-md-8">
                                    <input id="email" type="email"
                                        class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email"
                                        value="{{ old('email') }}" >
    
                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="city" class="col-md-2 col-form-label text-md-right">{{ __('City') }}</label>
                                <div class="col-md-8">
                                    <input id="city" type="text"
                                        class="form-control" name="city"
                                        value="{{ old('city') }}" >
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="country"
                                    class="col-md-2 col-form-label text-md-right">{{ __('Country') }}</label>
                                <div class="col-md-8">
                                    <input id="country" type="text"
                                        class="form-control"
                                        name="country" value="{{ old('country') }}" >
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="gender" class="col-md-2 col-form-label text-md-right">{{ __('Gender') }}</label>
                                <div class="col-md-8">
                                    <div class="form-control">
                                        <div class="form-check form-check-inline">
                                            <input type="radio" id="male" name="gender" class="form-check-input"
                                                value="male">
                                            <label for="male" class="form-check-label">Male</label><br>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input type="radio" id="female" name="gender" class="form-check-input"
                                                value="female">
                                            <label for="female" class="form-check-label">Female</label><br>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input type="radio" id="other" name="gender" class="form-check-input"
                                                value="other">
                                            <label for="other" class="form-check-label">Other</label>
                                        </div>
                                    </div>
    
                                    @if ($errors->has('gender'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('gender') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
    
                            <div class="form-group row mb-0">
                                <div class="col-md-2 offset-md-5">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        {{ __('Search') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="row">
        <div class="col-md-10 offset-md-1">
            <table class="table" style="margin-top: 20px;">
                <thead>
                    <th style="width: 20%">User Name</th>
                    <th style="width: 20%">Email</th>
                    <th style="width: 20%">Address</th>
                    <th style="width: 15%">No. of Post</th>
                    <th style="width: 10%">Gender</th>
                    <th style="width: 10%">Age</th>
                    <th style="width: 5%"></th>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->city.", ".$user->country }}</td>
                            <td>{{ $user->posts->count() }}</td>
                            <td>{{ $user->gender }}</td>
                            <td>{{ $user->age." years" }}</td>
                            
                            <td>
                                <div class="row">
                                    <a href="{{ route('admin.users.show', $user->id)}}" class="btn btn-primary btn-block">View</a>
                                    {!! Form::open(['route'=>['admin.users.update', $user->id], 'method' => 'PUT']) !!}
                                    {!! Form::submit($user->block ? 'Unblock' : 'Block', ['class'=>$user->block ? 'btn btn-danger btn-block' : 'btn btn-warning btn-block', 'style'=>'margin-top: 10px; width: 80px;']) !!}
                                    {!! Form::close() !!}
                                    {!! Form::open(['route'=>['admin.users.destroy', $user->id], 'method' => 'DELETE']) !!}
                                    {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-block', 'style'=>'margin-top: 10px; width: 80px;']) !!}
                                    {!! Form::close() !!}
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            
            <hr>

            <div class="" style="display: flex; justify-content: center;">
                {!! $users->links(); !!}
            </div>
        </div>
    </div>
@endsection